### ISSUE TITLE
More similar/More surprising slider bar appears to not be working

### ISSUE THREAD

**Issue by cjativa** [BarnesFoundation/Barnes-Online-Collection#170]
The slider works in that you can move it around and select a different value, but it continues to show the same visually related results -- it never changes. 

https://collection.barnesfoundation.org/objects/5674/Nude-in-a-Landscape-(Nu-dans-un-paysage)/

**Comment by snaftzger** [comment]
Increasing the `size()` function to something like 800 in `getRelatedObjects` in `app.js` gives us the desired results of varied visual related results, but, it also causes a massive slow down in performance. Server-side issue!
